# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chris Gaunt
description:      'Full-stack web developer and hobbyist game developer, having a blast developing with the Unity game engine.'
url:              http://chrisgaunt.com
baseurl:          /

author:
  name:           'Chris Gaunt'
  url:            https://twitter.com/ChrisGaunt

excerpt_separator: "<!-- more -->"
paginate:         5

# Custom vars
version:          2.1.0

repository:          https://github.com/chrisgaunt/chrisgaunt.github.io

plugins:
  - jekyll-redirect-from
